### ISSUE TITLE
IPFilter /Silent Task will not run because it does not detect my Portable torrent client

### ISSUE THREAD

**Issue by KirkH420** [DavidMoore/ipfilter#84] opened 2022-02-19 10:10 UTC
The task actually does not download anything and when I looked at the log file produced by IPFilter, it says:

IPFilter.exe Information: 0 : Arguments: /silent
IPFilter.exe Information: 0 : Running IPFilter in silent mode
IPFilter.exe Warning: 0 : No BitTorrent applications found. Nothing to do, so exiting.

Now, I should also add that my qBittorrent is actually qBittorrentPortable.exe (From PortableApps.com), so it's not actually installed. However, I wasn't actually wanting to use the Task. What I was actually trying to do was use IPFilter /silent on the command line.

I wrote a batch script that launches JacketTray.exe, then launches qBittorrent, and I was going to have it launch IPFilter /Silent which I thought would just go ahead and download my filter list at that point, but it fails due to whatever Registry check that it's doing.

Maybe there are some command line switches that I don't know about that I could use instead? Or maybe in the future there could be a /Force switch so it could be used in situations like mine? IPFilter /Silent /Force

**Comment by Corsair-63** [comment] 2022-03-11 10:01
Same Issue, I've done a schedule task with /silent and seen in log that it's not updated because not found torrent app, I've installed PicoTorrent, but if I run manually it downloads the IPFilter file.

**Comment by DavidMoore** [comment] 2023-03-30 12:02
I think what I could do here is check if I can see `qBittorrentPortable.exe` is running; then I'll be able to find where it's running from and drop the filter into that directory.

There are actually more command-line options but I'll probably not document those until I do the full rewrite.

**Comment by DavidMoore** [comment] 2023-08-18 10:21
I guess this is something of a duplicate of #61 which is fixed and ready to release.

Also have following related issues that are being worked on:

- #28 
- #79

**Comment by DavidMoore** [comment] 2023-08-19 04:03
Fixed in 3.0.4

**Closed by DavidMoore** 2023-08-19 04:03 UTC
Labels: bug, fixed
