### ISSUE TITLE
IPFilter Installation

### ISSUE THREAD

**Issue by no1bigfoot** [DavidMoore/ipfilter#21] opened 2016-04-19 16:07 UTC
I am attempting to install the latest version from your webpage, but I am getting the following error:
"Unable to update the password.  The value provided for the new password contains values that are not allowed in passwords."
P.S. Great software by the way... been using it for years now!

**Comment by DavidMoore** [comment] 2016-04-20 06:31
Hi. Were you doing an update from the previous version, or are you doing a new clean install?
P.S. Thank you :)

**Comment by no1bigfoot** [comment] 2016-04-20 12:30
I was doing an update from the previous version... should I uninstall and then do a clean install?

**Comment by DavidMoore** [comment] 2016-04-21 06:17
Try downloading the new installer manually from https://davidmoore.github.io/ipfilter/ and see if that upgrades for you. And if that doesn't work, yes, uninstall and try a clean install.

I think the problem is that it launches the upgrade directly instead of downloading it first, so I'm going to try and fix that part of the upgrade now.

**Comment by DavidMoore** [comment] 2016-05-18 01:16
I'm going to close this as there hasn't been a reply for a while. Feel free to re-open if you still have an issue.

**Closed by DavidMoore** 2016-05-18 01:16 UTC
